/**:
  ros__parameters:
    proportional_limitation : true
    antiwindup_cte : 1.0
    alpha: 0.3
    trajectory_following:
      position_Kp: 
        x: 0.4
        y: 0.4
        z: 0.4
      position_Ki:
        x: 0.0001
        y: 0.0001
        z: 0.0001
      position_Kd: 
        x: 0.0
        y: 0.0
        z: 0.0
    position_following:
      position_Kp: 
        x: 0.5
        y: 0.5
        z: 0.5
      position_Ki:
        x: 0.0
        y: 0.0
        z: 0.0
      position_Kd: 
        x: 0.0
        y: 0.0
        z: 0.0
    yaw_speed_controller:
      Kp: 1.0
      Ki: 0.001
      Kd: 0.0