/**:
  ros__parameters:
    use_sim_time: False
  platform:
    ros__parameters:
      cmd_freq: 10.0  # Hz of platform commands send
      info_freq: 10.0  # Hz of platform info publish
      sensor_freq: 1.0  # Hz of platform sensor publish
      camera.freq: 20.0
      camera:
        image_width: 960 # Image width (px)
        image_height: 720 # Image height (px)
        camera_name: camera # Camera name
        camera_matrix: 
          rows: 3
          cols: 3
          data: [918.0303232813636, 0.0, 479.7876715778283, 0.0, 918.0303232813636, 357.08021389348835, 0.0, 0.0, 1.0]
        distortion_model: plumb_bob # Distortion model
        distortion_coefficients:
          rows: 1
          cols: 5
          data: [44.20612088636562, 123.60759734475832, 0.0009372218683105743, -0.0014859075669979194, 71.03474952009566]
        rectification_matrix:
          rows: 3
          cols: 3
          data: [1.0, 0.0,  0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
        projection_matrix:
          rows: 3
          cols: 4
          data: [918.0303232813636, 0.0, 479.7876715778283, 0.0, 0.0, 918.0303232813636, 357.08021389348835, 0.0, 0.0, 0.0, 1.0, 0.0]
  state_estimator:
    ros__parameters:
      plugin_name: mocap_pose
      use_ignition_tf: False
      rigid_body_name: "1"
      mocap_topic: "/mocap/rigid_bodies"
      twist_smooth_filter_cte: 0.1
      orientation_smooth_filter_cte: 0.1
  controller_manager:
    ros__parameters:
      plugin_name: pid_speed_controller
      cmd_freq: 100.0  # Hz (default: 100.0)
      info_freq: 10.0  # Hz (default: 10.0)
      odom_frame_id: "odom"
      base_frame_id: "base_link"
      use_bypass: true
  TakeoffBehavior:
    ros__parameters:
      takeoff_plugin_name: takeoff_plugin_platform
      takeoff_height: 1.0  # [m]
      takeoff_speed: 0.2  # [m/s]
      takeoff_threshold: 0.1  # [m]
      tf_timeout_threshold: 0.5  # [s]
  LandBehavior:
    ros__parameters:
      land_plugin_name: land_plugin_platform
      land_speed: 0.4  # [m/s]
      tf_timeout_threshold: 0.5  # [s]
  GoToBehavior:
    ros__parameters:
      go_to_plugin_name: go_to_plugin_position
      go_to_speed: 0.5  # [m/s]
      go_to_threshold: 0.2  # [m]
      tf_timeout_threshold: 0.5  # [s]
  FollowPathBehavior:
    ros__parameters:
      follow_path_plugin_name: follow_path_plugin_position
      follow_path_speed: 0.5  # [m/s]
      follow_path_threshold: 0.1  # [m]
      tf_timeout_threshold: 0.5  # [s]